### ISSUE TITLE
Remove unnecessary columns from Language class

### ISSUE THREAD

**Issue by xrotwang** [lexibank/halenepal#10]
In https://github.com/lexibank/halenepal/blob/bcdcda2c6e6c9e4d84d4ca82e1d0132a49ccf8a4/lexibank_halenepal.py#L28-L32
`Latitude`, `Longitude` and `Glottolog_name` are unnecessary. There already exist in the base class:
https://github.com/lexibank/pylexibank/blob/434fa0890ba15e3f1a3ceb446edee0456b020bd2/src/pylexibank/models.py#L24-L27

**Comment by LinguList** [comment]
Really? I ran into errors last week when I did not assign them explicitly. I think I even filed a bug report on this (?). Has this been closed since then?

**Comment by xrotwang** [comment]
I added latitude and longitude recently, but Glottolog_Name was there all
along. Note the difference in capitalization,  though.

Johann-Mattis List <notifications@github.com> schrieb am Mi., 6. Nov. 2019,
23:27:

**Comment by chrzyki** [comment]
Opened a PR with updates

**Comment by chrzyki** [comment]
Done in #11.
