### ISSUE TITLE
Fix concept assignments in the data, as shown in buildbot error.

### ISSUE THREAD

**Issue by LinguList** [lexibank/halenepal#14]
* https://buildbot.clld.org/#/builders/87/builds/4

**Comment by chrzyki** [comment]
Wow, this confused me for a second. Since the build definitely worked during the last release & CLDF creation worked and nothing changed in the repository what might have caused this?

All the lookups fail for SRCIDs with trailing zeroes which were removed in the concept list in Concepticon during this commit (and others, might have to check): https://github.com/concepticon/concepticon-data/commit/805c5d9f3f3ace1cca14c8d8d3540d0d6ad60a29

Due to this, the STEDT ID lookups fail.

**Comment by chrzyki** [comment]
Oh, and I guess thanks to buildbot for noticing. :)

**Comment by LinguList** [comment]
I think, we need to re-install the trailing ids.

**Comment by chrzyki** [comment]
Doing that right now, PR is in the works.

**Comment by LinguList** [comment]
I was expecting exactly this, that somebody made something with the IDs, but did not have time to look closely into it (thanks, @chrzyki). The problem we face here is important, as it shows that we need to be more careful when adding lists to concepticon. I assume, somebody checked the list, corrected small mappings, and used libreoffice, where the instance is interpreted as a number and therefore trailing zeros are deleted.

**Comment by LinguList** [comment]
Yep, exactly, when looking at the commit. We need to be more careful when accepting concepticon PRs, as these things should not easily be modified. That's why our "editor" system is already a good way to make sure this happens less often.

**Comment by chrzyki** [comment]
Agreed!

**Comment by LinguList** [comment]
@SimonGreenhill, @xrotwang, @tresoldi, calling this to your attention as an example that we need to be careful with so many different aspects like concepticon and glottolog, that we do not make too strong modifications now in our reference catalogs at once. I don't know if there's a mechanism to save us from this, though.

**Comment by LinguList** [comment]
And since the HALE list is anyway exceptional, I have the hope that this won't happen too much with other datasets.

**Comment by xrotwang** [comment]
I think the principle here would be to limit PRs to **essential** changes. (Just like you should **not** mix PEP8 or similar changes into a bugfix commit for software - but I know that's hard to resist.)

It has to sink in that **all parts of the data in concepticon** are the "external interface", i.e. something other software (or people) may rely on.

**Comment by SimonGreenhill** [comment]
Hmm, can we add a regression test into concepticon-data for this specific change? I can see this easily happening again.

**Comment by LinguList** [comment]
What happened here was that we were made aware of the change by Annika:

https://github.com/concepticon/concepticon-data/pull/749

But nobody reacted. So it's on me, I assume, as I was reviewing the PR.

I think a first step is our reviewer/editor system in concepticon now:
editors need to pay much closer attention to the PRs and make sure that
these changes are not made unwillingly.

**Comment by xrotwang** [comment]
@SimonGreenhill I think the "proper regression test" for this kind of thing is reviewing pull request :) - and to make that possible, keep PRs to a reviewable size.

**Comment by chrzyki** [comment]
Fixed, depends on updated Concepticon for buildbot.

**Comment by chrzyki** [comment]
Will re-run this with a new Concepticon release whenever it is ready.
